#
# Module manifest for module 'mdatp-pwsh'
#
# Generated by: Tim Small
#
# Generated on: 7/25/2020
#

@{

    RootModule         = "AzSentinel.dll"
    ModuleVersion      = "2020.10.0"
    # CompatiblePSEditions = @()
    GUID               = "6063510f-19df-4196-bb8d-82df80d66e85"
    Author             = "Tim Small"
    CompanyName        = "Smalls.Online"
    Copyright          = "2020"
    Description        = "Azure Sentinel PowerShell Module"
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # ClrVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    RequiredAssemblies = "Microsoft.Identity.Client.dll", "System.Text.Json.dll"
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()

    # FunctionsToExport  = ""

    CmdletsToExport    = @(
        "Set-SentinelModuleConfig",
        "Connect-Sentinel",
        "Get-SentinelSessionClient",
        "Get-SentinelIncident"
    )

    # VariablesToExport  = "*"

    # AliasesToExport    = "*"

    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()

    PrivateData        = @{

        PSData = @{

            # Tags = @()

            # LicenseUri = ""

            # ProjectUri = ""

            # IconUri = ''

            # ReleaseNotes = ''

            Prerelease = "preview-01"

            # RequireLicenseAcceptance = $false

            # ExternalModuleDependencies = @()

        }

    }

    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''

}
